# Generated by Django 4.2 on 2023-04-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Email", models.CharField(max_length=150)),
                ("Password", models.CharField(max_length=200)),
                ("Re_Password", models.CharField(max_length=200)),
            ],
        ),
    ]
